### ISSUE TITLE
Different view of compare view

### ISSUE THREAD

**Issue by BartDuwez** [moxfield/moxfield-public#41]
I made a deck called "Inventory", this way I can compare whats in my inventory and whats in a deck.

Would it be possible to view "compare view" as a written list instead of images?

My inventory is getting bigger so the loading of the compare view is getting slower.
All the images are making the page really big, so I have to scroll a lot.
Searching is harder.

Choosing this option should be remembered by the app.

**Comment by harryfino** [comment]
I understand the some people are trying to work around the fact that we don't have collections yet, but decks should not be used for this purpose, which is why the functionality around decks doesn't support it very well. We will also be putting a limit on deck size shortly, so that people will not be able to do this, as it negatively affects the performance of everyone on the site.

On the bright side, we have an official collection feature coming by the end of this year, which will have full support for showing what's in your collection in your decks. You can gain beta access to this now as a Patreon subscriber.
